# --- after generated_script = await gen_func(...) ---
# send the generated script to the frontend so the socket window shows it immediately
try:
    await websocket.send_text(json.dumps({
        "status": "GENERATED",
        "log": "Script generated by generator",
        "script": generated_script
    }))
except Exception:
    # if the script is huge and socket chokes, fall back to preview
    await websocket.send_text(json.dumps({
        "status": "GENERATED",
        "log": "Script generated (preview)",
        "script_preview": generated_script[:2000],
        "script_length": len(generated_script)
    }))
# then continue validation
if not generated_script or not isinstance(generated_script, str):
    raise RuntimeError("Generated script empty/invalid")




# after you call azure/openai and have `response`
# --- robust extraction of content from SDK response ---
try:
    # many Azure SDKs return choice.message as an object with .content
    msg = response.choices[0].message
    raw_text = getattr(msg, "content", None)

    # some clients return text differently; try fallback:
    if raw_text is None:
        # older / alternative SDKs sometimes return 'text' or choices[0].text
        raw_text = getattr(response.choices[0], "text", None)

    if raw_text is None:
        raise RuntimeError("Azure OpenAI returned no content")

except Exception as e:
    if logger:
        logger.error(LogCategory.GENERATION, f"Azure OpenAI error: {str(e)}")
    raise RuntimeError(f"Azure OpenAI script generation failed: {str(e)}")
